% -------------------------------------------------------------------
%  Generated by MATLAB on 21-Jan-2022 16:29:41
%  MATLAB version: 9.11.0.1769968 (R2021b)
% -------------------------------------------------------------------
                                      

Th = 50;

baseFileName = 'mvn_mag_l2_2015001pc_20150101_v01_r01.sts';

clat = -5;

clon = 137;

downsample = 1;

filePattern = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN_Tracks\201' ...
               '5\01\*.sts'];

fullFileName = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN_Tracks\20' ...
                '15\01\mvn_mag_l2_2015001pc_20150101_v01_r01.sts'];

h = 200;

jpegFiles = struct;
jpegFiles(1, 1).name = 'mvn_mag_l2_2015001pc_20150101_v01_r01.sts';
jpegFiles(1, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN' ...
                          '_Tracks\2015\01'];
jpegFiles(1, 1).date = '18-May-2015 20:42:00';
jpegFiles(1, 1).bytes = 4.14721372E+8;
jpegFiles(1, 1).isdir = false;
jpegFiles(1, 1).datenum = 736102.8625;
jpegFiles(2, 1).name = 'mvn_mag_l2_2015002pc_20150102_v01_r01.sts';
jpegFiles(2, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN' ...
                          '_Tracks\2015\01'];
jpegFiles(2, 1).date = '18-May-2015 20:42:54';
jpegFiles(2, 1).bytes = 4.14692572E+8;
jpegFiles(2, 1).isdir = false;
jpegFiles(2, 1).datenum = 736102.863125;
jpegFiles(3, 1).name = 'mvn_mag_l2_2015003pc_20150103_v01_r01.sts';
jpegFiles(3, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN' ...
                          '_Tracks\2015\01'];
jpegFiles(3, 1).date = '18-May-2015 20:43:30';
jpegFiles(3, 1).bytes = 4.14740572E+8;
jpegFiles(3, 1).isdir = false;
jpegFiles(3, 1).datenum = 736102.86354166665;
jpegFiles(4, 1).name = 'mvn_mag_l2_2015004pc_20150104_v01_r01.sts';
jpegFiles(4, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN' ...
                          '_Tracks\2015\01'];
jpegFiles(4, 1).date = '18-May-2015 20:44:50';
jpegFiles(4, 1).bytes = 4.14730972E+8;
jpegFiles(4, 1).isdir = false;
jpegFiles(4, 1).datenum = 736102.86446759256;
jpegFiles(5, 1).name = 'mvn_mag_l2_2015005pc_20150105_v01_r01.sts';
jpegFiles(5, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN' ...
                          '_Tracks\2015\01'];
jpegFiles(5, 1).date = '18-May-2015 20:45:30';
jpegFiles(5, 1).bytes = 4.14730972E+8;
jpegFiles(5, 1).isdir = false;
jpegFiles(5, 1).datenum = 736102.86493055557;
jpegFiles(6, 1).name = 'mvn_mag_l2_2015006pc_20150106_v01_r01.sts';
jpegFiles(6, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN' ...
                          '_Tracks\2015\01'];
jpegFiles(6, 1).date = '18-May-2015 20:46:48';
jpegFiles(6, 1).bytes = 4.14529372E+8;
jpegFiles(6, 1).isdir = false;
jpegFiles(6, 1).datenum = 736102.86583333334;
jpegFiles(7, 1).name = 'mvn_mag_l2_2015007pc_20150107_v01_r01.sts';
jpegFiles(7, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN' ...
                          '_Tracks\2015\01'];
jpegFiles(7, 1).date = '18-May-2015 20:47:14';
jpegFiles(7, 1).bytes = 4.14730972E+8;
jpegFiles(7, 1).isdir = false;
jpegFiles(7, 1).datenum = 736102.86613425927;
jpegFiles(8, 1).name = 'mvn_mag_l2_2015008pc_20150108_v01_r01.sts';
jpegFiles(8, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN' ...
                          '_Tracks\2015\01'];
jpegFiles(8, 1).date = '18-May-2015 20:47:38';
jpegFiles(8, 1).bytes = 4.14735772E+8;
jpegFiles(8, 1).isdir = false;
jpegFiles(8, 1).datenum = 736102.866412037;
jpegFiles(9, 1).name = 'mvn_mag_l2_2015009pc_20150109_v01_r01.sts';
jpegFiles(9, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN' ...
                          '_Tracks\2015\01'];
jpegFiles(9, 1).date = '18-May-2015 20:48:42';
jpegFiles(9, 1).bytes = 4.14735772E+8;
jpegFiles(9, 1).isdir = false;
jpegFiles(9, 1).datenum = 736102.86715277773;
jpegFiles(10, 1).name = 'mvn_mag_l2_2015010pc_20150110_v01_r01.sts';
jpegFiles(10, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(10, 1).date = '18-May-2015 20:51:38';
jpegFiles(10, 1).bytes = 4.12638172E+8;
jpegFiles(10, 1).isdir = false;
jpegFiles(10, 1).datenum = 736102.86918981478;
jpegFiles(11, 1).name = 'mvn_mag_l2_2015011pc_20150111_v01_r01.sts';
jpegFiles(11, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(11, 1).date = '18-May-2015 20:52:20';
jpegFiles(11, 1).bytes = 4.14730972E+8;
jpegFiles(11, 1).isdir = false;
jpegFiles(11, 1).datenum = 736102.86967592593;
jpegFiles(12, 1).name = 'mvn_mag_l2_2015012pc_20150112_v01_r01.sts';
jpegFiles(12, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(12, 1).date = '18-May-2015 20:53:20';
jpegFiles(12, 1).bytes = 4.14730972E+8;
jpegFiles(12, 1).isdir = false;
jpegFiles(12, 1).datenum = 736102.87037037034;
jpegFiles(13, 1).name = 'mvn_mag_l2_2015013pc_20150113_v01_r01.sts';
jpegFiles(13, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(13, 1).date = '18-May-2015 20:54:02';
jpegFiles(13, 1).bytes = 4.14730972E+8;
jpegFiles(13, 1).isdir = false;
jpegFiles(13, 1).datenum = 736102.87085648149;
jpegFiles(14, 1).name = 'mvn_mag_l2_2015014pc_20150114_v01_r01.sts';
jpegFiles(14, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(14, 1).date = '18-May-2015 20:55:18';
jpegFiles(14, 1).bytes = 4.14730972E+8;
jpegFiles(14, 1).isdir = false;
jpegFiles(14, 1).datenum = 736102.87173611112;
jpegFiles(15, 1).name = 'mvn_mag_l2_2015015pc_20150115_v01_r01.sts';
jpegFiles(15, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(15, 1).date = '18-May-2015 20:56:14';
jpegFiles(15, 1).bytes = 4.14730972E+8;
jpegFiles(15, 1).isdir = false;
jpegFiles(15, 1).datenum = 736102.87238425924;
jpegFiles(16, 1).name = 'mvn_mag_l2_2015016pc_20150116_v01_r01.sts';
jpegFiles(16, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(16, 1).date = '18-May-2015 20:57:18';
jpegFiles(16, 1).bytes = 4.14726172E+8;
jpegFiles(16, 1).isdir = false;
jpegFiles(16, 1).datenum = 736102.873125;
jpegFiles(17, 1).name = 'mvn_mag_l2_2015017pc_20150117_v01_r01.sts';
jpegFiles(17, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(17, 1).date = '18-May-2015 20:59:04';
jpegFiles(17, 1).bytes = 4.14735772E+8;
jpegFiles(17, 1).isdir = false;
jpegFiles(17, 1).datenum = 736102.87435185187;
jpegFiles(18, 1).name = 'mvn_mag_l2_2015018pc_20150118_v01_r01.sts';
jpegFiles(18, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(18, 1).date = '18-May-2015 20:59:38';
jpegFiles(18, 1).bytes = 4.14730972E+8;
jpegFiles(18, 1).isdir = false;
jpegFiles(18, 1).datenum = 736102.87474537035;
jpegFiles(19, 1).name = 'mvn_mag_l2_2015019pc_20150119_v01_r01.sts';
jpegFiles(19, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(19, 1).date = '18-May-2015 21:00:54';
jpegFiles(19, 1).bytes = 4.14740572E+8;
jpegFiles(19, 1).isdir = false;
jpegFiles(19, 1).datenum = 736102.875625;
jpegFiles(20, 1).name = 'mvn_mag_l2_2015020pc_20150120_v01_r01.sts';
jpegFiles(20, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(20, 1).date = '18-May-2015 21:01:20';
jpegFiles(20, 1).bytes = 4.14442972E+8;
jpegFiles(20, 1).isdir = false;
jpegFiles(20, 1).datenum = 736102.87592592591;
jpegFiles(21, 1).name = 'mvn_mag_l2_2015021pc_20150121_v01_r01.sts';
jpegFiles(21, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(21, 1).date = '18-May-2015 21:01:52';
jpegFiles(21, 1).bytes = 4.14721372E+8;
jpegFiles(21, 1).isdir = false;
jpegFiles(21, 1).datenum = 736102.87629629625;
jpegFiles(22, 1).name = 'mvn_mag_l2_2015022pc_20150122_v01_r01.sts';
jpegFiles(22, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(22, 1).date = '18-May-2015 21:03:18';
jpegFiles(22, 1).bytes = 4.14682972E+8;
jpegFiles(22, 1).isdir = false;
jpegFiles(22, 1).datenum = 736102.87729166669;
jpegFiles(23, 1).name = 'mvn_mag_l2_2015023pc_20150123_v01_r01.sts';
jpegFiles(23, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(23, 1).date = '18-May-2015 21:04:54';
jpegFiles(23, 1).bytes = 4.14730972E+8;
jpegFiles(23, 1).isdir = false;
jpegFiles(23, 1).datenum = 736102.87840277783;
jpegFiles(24, 1).name = 'mvn_mag_l2_2015024pc_20150124_v01_r01.sts';
jpegFiles(24, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(24, 1).date = '18-May-2015 21:05:38';
jpegFiles(24, 1).bytes = 4.14452572E+8;
jpegFiles(24, 1).isdir = false;
jpegFiles(24, 1).datenum = 736102.878912037;
jpegFiles(25, 1).name = 'mvn_mag_l2_2015025pc_20150125_v01_r01.sts';
jpegFiles(25, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(25, 1).date = '18-May-2015 21:07:08';
jpegFiles(25, 1).bytes = 4.14730972E+8;
jpegFiles(25, 1).isdir = false;
jpegFiles(25, 1).datenum = 736102.87995370373;
jpegFiles(26, 1).name = 'mvn_mag_l2_2015026pc_20150126_v01_r01.sts';
jpegFiles(26, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(26, 1).date = '18-May-2015 21:08:58';
jpegFiles(26, 1).bytes = 4.14548572E+8;
jpegFiles(26, 1).isdir = false;
jpegFiles(26, 1).datenum = 736102.88122685184;
jpegFiles(27, 1).name = 'mvn_mag_l2_2015027pc_20150127_v01_r01.sts';
jpegFiles(27, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(27, 1).date = '18-May-2015 21:10:54';
jpegFiles(27, 1).bytes = 4.12532572E+8;
jpegFiles(27, 1).isdir = false;
jpegFiles(27, 1).datenum = 736102.88256944448;
jpegFiles(28, 1).name = 'mvn_mag_l2_2015028pc_20150128_v01_r01.sts';
jpegFiles(28, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(28, 1).date = '18-May-2015 21:11:30';
jpegFiles(28, 1).bytes = 4.14654172E+8;
jpegFiles(28, 1).isdir = false;
jpegFiles(28, 1).datenum = 736102.8829861111;
jpegFiles(29, 1).name = 'mvn_mag_l2_2015029pc_20150129_v01_r01.sts';
jpegFiles(29, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(29, 1).date = '18-May-2015 21:13:12';
jpegFiles(29, 1).bytes = 4.14730972E+8;
jpegFiles(29, 1).isdir = false;
jpegFiles(29, 1).datenum = 736102.88416666666;
jpegFiles(30, 1).name = 'mvn_mag_l2_2015030pc_20150130_v01_r01.sts';
jpegFiles(30, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(30, 1).date = '18-May-2015 21:13:38';
jpegFiles(30, 1).bytes = 4.14663772E+8;
jpegFiles(30, 1).isdir = false;
jpegFiles(30, 1).datenum = 736102.88446759258;
jpegFiles(31, 1).name = 'mvn_mag_l2_2015031pc_20150131_v01_r01.sts';
jpegFiles(31, 1).folder = ['C:\Users\Zain\Documents\_Research\Mars\MAVE' ...
                           'N_Tracks\2015\01'];
jpegFiles(31, 1).date = '18-May-2015 21:14:08';
jpegFiles(31, 1).bytes = 4.14730972E+8;
jpegFiles(31, 1).isdir = false;
jpegFiles(31, 1).datenum = 736102.88481481478;

k = 1;

myFolder = ['C:\Users\Zain\Documents\_Research\Mars\MAVEN_Tracks\2015\0' ...
            '1'];

